global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "storage_api"
    scrape_interval: 10s
    static_configs:
      - targets: ["storage_api:5000"]
    metrics_path: /api/metrics
