---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
        - name: storage-api
          image: storage-api:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: storage-api
spec:
  selector:
    app: storage-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      