{
 "title": "Storage Api Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(http_request_duration_seconds_count{job=\"storage_api\"}) by (status)"
    }
   ]
  },
  {
   "title": "HTTP Status Codes Rate(?)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count{job=\"storage_api\"}[5m])) by (status)"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{job=\"storage_api\", status!=\"500\"}) / sum(http_request_duration_seconds_count{job=\"storage_api\", status!=\"500\"})",
     "legendFormat": "Average Duration"
    }
   ]
  }
 ]
}