apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
      - name: storage-api
        image: storage-api-image:tag
        ports:
        - containerPort: 5000
